inherit_from:
- .rubocop_airbnb.yml

Allcops:
 Exclude:
  - "db/**/*"
  - "bin/*"
  - "config/environments/*"
  - "config/application.rb"
  - "config/initializers/*"
  - "config/spring.rb"
  - "lib/tasks/*"
  - "vender/**/*"
  - "path/ruby"

